name: 'ali-oss-website-action'
description: 'Deploy your website to aliyun OSS, auto create buckets'
author: 'Zeb Wu <wzb3422@gmail.com>'
branding:
  icon: 'upload'
  color: 'gray-dark'
inputs:
  folder:
    description: 'The folder to be uploaded'
    required: true
  accessKeyId:
    description: 'Aliyun accessKeyId.'
    required: true
  accessKeySecret:
    description: 'Aliyun accessKeySecret.'
    required: true
  bucket:
    description: 'Name of OSS bucket, one would be created if no corresponding bucket is found'
    required: true
  endpoint:
    description: 'Endpoint of OSS bucket'
    required: true
  configureWebsite:
    description: 'Configure OSS website settings'
    required: false
    default: 'false'
  indexPage:
    description: 'Index page of OSS website'
    required: false
  404Page:
    description: '404 Not Found page of OSS website'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
