name: Local Action Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test local oss upload action
    steps:
        # load repo to /github/workspace
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Upload files to Aliyun OSS
        uses: ./ # Uses an action in the root directory
        id: upload
        with:
          folder: example
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: ncuhome-zebwu-test
          endpoint: oss-cn-hangzhou.aliyuncs.com
          incremental: true
